# Generated by Django 3.2 on 2024-04-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20240426_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
